version: '3'

services:

  nginx:
    image: nginx:1.27
    volumes:
      - ./:/var/www/html
      - ./.docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/conf/sites/:/etc/nginx/sites-available
      - ./.docker/conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - php83-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=HostRegexp(`stv.test.local`)"
      - "traefik.http.middlewares.allow-headers.headers.customRequestHeaders.allowedHeaders=*"
    networks:
      - traefik

  php83-fpm:
    build:
      dockerfile: .docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=${USERNAME:-developer}
    volumes:
      - ./:/var/www/html
      - ./.docker/conf/00-debug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - traefik
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file: .env

  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    #      - ./../pgsql/13/data/:/var/lib/postgresql/data
    networks:
      - traefik
    ports:
      - '5432:5432'

networks:
  traefik:
    external: true

volumes:
  pgdata: